import { Instrument } from '../../types/instrument';
import { TestEquipment } from '../../types/equipment';
import { Laboratory, UserProfile } from '../../types/user';
import { TestSession } from '../../types/testSession';
import { TestReport } from '../../types/report';

export const SEED_LABORATORY: Laboratory = {
  id: 'LAB-IND-001',
  name: 'National Legal Metrology Testing Centre (Apex Metrology Lab)',
  legalAddress: 'Plot 14, Metrology Complex, Technology Park, OIML Reference Center',
  city: 'New Delhi',
  country: 'India',
  accreditationNumber: 'NABL-ISO/IEC-17025-MET-2026-089',
  accreditationBody: 'National Accreditation Board for Testing and Calibration Laboratories',
  contactEmail: 'nawi.testing@metrology.gov.in',
  contactPhone: '+91-11-2584-9000',
  logoUrl: '',
};

export const SEED_USERS: UserProfile[] = [
  {
    id: 'USR-TECH-01',
    email: 'aniket.technician@lab.metrology.org',
    fullName: 'Aniket Gond',
    role: 'LAB_TECHNICIAN',
    designation: 'Senior Legal Metrology Testing Officer',
    laboratoryId: 'LAB-IND-001',
    laboratoryName: 'National Legal Metrology Testing Centre',
    signatureText: 'A. Gond, M.Tech (Metrology)',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'USR-REV-01',
    email: 'dr.verma.reviewer@lab.metrology.org',
    fullName: 'Dr. Rajesh Verma',
    role: 'REVIEWER_OFFICER',
    designation: 'Principal Legal Metrology Officer & Technical Assessor',
    laboratoryId: 'LAB-IND-001',
    laboratoryName: 'National Legal Metrology Testing Centre',
    signatureText: 'Dr. R. Verma, Ph.D. (Applied Metrology)',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'USR-ADM-01',
    email: 'admin.director@lab.metrology.org',
    fullName: 'Director S. Ramanathan',
    role: 'ADMIN',
    designation: 'Director General of Legal Metrology',
    laboratoryId: 'LAB-IND-001',
    laboratoryName: 'National Legal Metrology Testing Centre',
    signatureText: 'S. Ramanathan, Director General',
    createdAt: '2026-01-01T09:00:00Z',
  },
];

export const SEED_EQUIPMENT: TestEquipment[] = [
  {
    id: 'EQ-WT-E2-01',
    equipmentIdTag: 'STD-E2-WT-001',
    name: 'Standard Mass Set Class E2 (1 mg – 1 kg)',
    manufacturer: 'Häfner Weights GmbH',
    model: 'E2 Precision Stainless Cylindrical',
    serialNumber: 'HAF-E2-993821',
    equipmentType: 'Standard Weights',
    weightClass: 'E2',
    nominalRange: '1 mg to 1000 g',
    uncertainty: 'U = 0.016 mg to 0.5 mg (k=2)',
    calibrationCertificateNumber: 'CAL-NPL-2026-E2-4412',
    calibratedBy: 'National Physical Laboratory',
    calibrationDate: '2026-01-10',
    calibrationExpiryDate: '2027-01-10',
    isExpired: false,
    status: 'ACTIVE',
    laboratoryId: 'LAB-IND-001',
  },
  {
    id: 'EQ-WT-F1-02',
    equipmentIdTag: 'STD-F1-WT-002',
    name: 'Cast Iron & Brass Standard Weights Class F1 (100 g – 50 kg)',
    manufacturer: 'Mettler Toledo Metrology',
    model: 'F1 Block & Knob Weights',
    serialNumber: 'MT-F1-884102',
    equipmentType: 'Standard Weights',
    weightClass: 'F1',
    nominalRange: '100 g to 50 kg',
    uncertainty: 'U = 1.6 mg to 80 mg (k=2)',
    calibrationCertificateNumber: 'CAL-NABL-2025-F1-8821',
    calibratedBy: 'Apex Metrology Calibration Services',
    calibrationDate: '2025-11-20',
    calibrationExpiryDate: '2026-11-20',
    isExpired: false,
    status: 'ACTIVE',
    laboratoryId: 'LAB-IND-001',
  },
  {
    id: 'EQ-WT-M1-03',
    equipmentIdTag: 'STD-M1-WT-003',
    name: 'Cast Iron Heavy Weights Class M1 (20 kg & 500 kg Grip Blocks)',
    manufacturer: 'Avery Weigh-Tronix',
    model: 'M1 Calibrated Test Weights',
    serialNumber: 'AV-M1-550912',
    equipmentType: 'Standard Weights',
    weightClass: 'M1',
    nominalRange: '20 kg to 5000 kg',
    uncertainty: 'U = 1.0 g to 25 g (k=2)',
    calibrationCertificateNumber: 'CAL-NABL-2025-M1-1099',
    calibratedBy: 'Heavy Standards Testing Bureau',
    calibrationDate: '2025-08-15',
    calibrationExpiryDate: '2026-08-15',
    isExpired: true, // Example expired equipment for compliance safety testing
    status: 'CALIBRATION_DUE',
    laboratoryId: 'LAB-IND-001',
  },
  {
    id: 'EQ-ENV-TH-01',
    equipmentIdTag: 'ENV-TH-LOG-01',
    name: 'Precision Digital Thermo-Hygrometer & Barometer',
    manufacturer: 'Testo AG',
    model: 'Testo 635-2 Metrology Baro',
    serialNumber: 'TESTO-635-90118',
    equipmentType: 'Thermometer / Hygrometer',
    nominalRange: '-20°C to +70°C / 0 to 100% RH / 300 to 1200 hPa',
    uncertainty: 'U(T)=0.1°C, U(RH)=1.2%, U(P)=0.5 hPa',
    calibrationCertificateNumber: 'CAL-ENV-2026-904',
    calibratedBy: 'National Climate Standards Lab',
    calibrationDate: '2026-02-01',
    calibrationExpiryDate: '2027-02-01',
    isExpired: false,
    status: 'ACTIVE',
    laboratoryId: 'LAB-IND-001',
  },
];

export const SEED_INSTRUMENTS: Instrument[] = [
  {
    id: 'INST-2026-001',
    instrumentIdTag: 'NAWI-BAL-001',
    manufacturer: 'Sartorius Lab Instruments GmbH',
    model: 'Cubis II Premium MSA225S',
    serialNumber: 'SAR-2026-881923',
    instrumentType: 'Electronic Balance',
    accuracyClass: 'CLASS_I',
    maxCapacity: 220,
    minCapacity: 0.01,
    verificationScaleInterval: 0.001, // e = 1 mg = 0.001 g
    actualScaleInterval: 0.0001, // d = 0.1 mg
    unit: 'g',
    numberOfIntervals: 220000, // n = 220 / 0.001 = 220,000
    tareType: 'Subtractive',
    maxTare: 220,
    loadReceptorType: 'Round Plate',
    numberOfSupportPoints: 1,
    platformDimensions: 'Diameter 90 mm Draft Shield Pan',
    softwareVersion: 'v4.12.08-OIML',
    powerSupply: '230V AC adapter (15V DC)',
    operatingTemperatureMin: 10,
    operatingTemperatureMax: 30,
    patternApprovalNumber: 'IND-PAT-2025-0042',
    markingDetails: 'CE M26 0122 / Class I / Max 220g / Min 10mg / e=1mg / d=0.1mg',
    laboratoryId: 'LAB-IND-001',
    components: [
      {
        id: 'CMP-LC-01',
        componentType: 'Load Cell',
        manufacturer: 'Sartorius Monolithic',
        model: 'MonoBloc High Resolution Cell',
        serialNumber: 'MB-2026-0912',
        maxCapacity: 250,
        unit: 'g',
      },
    ],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'INST-2026-002',
    instrumentIdTag: 'NAWI-SCL-002',
    manufacturer: 'Mettler Toledo Industrial',
    model: 'BBA231 Multi-Purpose Industrial Bench Scale',
    serialNumber: 'MT-BBA-771290',
    instrumentType: 'Bench Scale',
    accuracyClass: 'CLASS_III',
    maxCapacity: 15,
    minCapacity: 0.1,
    verificationScaleInterval: 0.005, // e = 5 g = 0.005 kg
    actualScaleInterval: 0.005, // d = e
    unit: 'kg',
    numberOfIntervals: 3000, // n = 15 / 0.005 = 3000
    tareType: 'Subtractive',
    maxTare: 15,
    loadReceptorType: 'Rectangular Platform',
    numberOfSupportPoints: 4,
    platformDimensions: '305 x 355 mm Stainless Steel',
    softwareVersion: 'v2.04',
    powerSupply: '230V AC 50Hz / Internal Rechargeable Lead-Acid',
    operatingTemperatureMin: -10,
    operatingTemperatureMax: 40,
    patternApprovalNumber: 'IND-PAT-2024-0891',
    markingDetails: 'Class III / Max 15kg / Min 100g / e=d=5g / T=-15kg',
    laboratoryId: 'LAB-IND-001',
    components: [
      {
        id: 'CMP-LC-02',
        componentType: 'Load Cell',
        manufacturer: 'Zemic Europe',
        model: 'L6E Single Point IP65',
        serialNumber: 'ZM-L6E-90412',
        maxCapacity: 20,
        unit: 'kg',
      },
    ],
    createdAt: '2026-02-10T11:30:00Z',
    updatedAt: '2026-02-10T11:30:00Z',
  },
  {
    id: 'INST-2026-003',
    instrumentIdTag: 'NAWI-PLT-003',
    manufacturer: 'Avery India Metrology Ltd.',
    model: 'ProPlatform 1500 Heavy Industrial Scale',
    serialNumber: 'AV-IND-551029',
    instrumentType: 'Floor / Platform Scale',
    accuracyClass: 'CLASS_III',
    maxCapacity: 1500,
    minCapacity: 10,
    verificationScaleInterval: 0.5, // e = 0.5 kg
    actualScaleInterval: 0.5,
    unit: 'kg',
    numberOfIntervals: 3000,
    tareType: 'Subtractive',
    maxTare: 1500,
    loadReceptorType: 'Rectangular Platform',
    numberOfSupportPoints: 4,
    platformDimensions: '1500 x 1500 mm Chequered Mild Steel',
    softwareVersion: 'E1205-v3.1',
    powerSupply: '230V AC 50Hz',
    operatingTemperatureMin: -10,
    operatingTemperatureMax: 40,
    patternApprovalNumber: 'IND-PAT-2023-0112',
    laboratoryId: 'LAB-IND-001',
    components: [],
    createdAt: '2026-02-15T14:00:00Z',
    updatedAt: '2026-02-15T14:00:00Z',
  },
];
